
cache:
  host: redis
  port: 6379
  db: 0
  password: ""

server:
  port: 8080

limiter:
  limitrequestperip: 5
  expiration: 5
  blockingtimeip: 300
  blockingtimetoken: 300

tokens:
  - token: "token_test1"
    limiter: 5
    expiration: 5
  - token: "token_test2"
    limiter: 10
    expiration : 5
